name: 'private repo rules'
description: 'Actions to allow and disallow a PR'
author: 'haider000'
inputs:
  rules: # change this
    required: false
    description: 'rules for allowing and disallowing pull requests'
    default: '["allow if from (.*) to (.*)"]'
  GITHUB_TOKEN: # change this
    required: true
    description: 'Token for accesing pr name'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
